/**
 * Viewport smoke snapshot. We can't run headless Chrome in CI without
 * puppeteer, so this test exercises the responsive CSS by reading the
 * generated stylesheet and asserting that the four breakpoints are
 * represented at the right widths.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

describe('responsive CSS', () => {
  const css = readFileSync(resolve(__dirname, '../../src/hub/styles.css'), 'utf8');

  it('defines a 640px (tablet) breakpoint', () => {
    expect(css).toMatch(/@media \(min-width: 640px\)/);
  });
  it('defines a 1024px (desktop) breakpoint', () => {
    expect(css).toMatch(/@media \(min-width: 1024px\)/);
  });
  it('defines a 1440px (wide) breakpoint', () => {
    expect(css).toMatch(/@media \(min-width: 1440px\)/);
  });
  it('defines a 639px (mobile max) breakpoint', () => {
    expect(css).toMatch(/@media \(max-width: 639px\)/);
  });
  it('respects prefers-reduced-motion', () => {
    expect(css).toMatch(/@media \(prefers-reduced-motion: reduce\)/);
  });
  it('forces 44px touch targets', () => {
    expect(css).toMatch(/min-height: 44px/);
  });
});

describe('viewport snapshot simulation', () => {
  const VIEWPORTS = [
    { name: '320-iphone', width: 320, height: 568 },
    { name: '768-tablet', width: 768, height: 1024 },
    { name: '1280-laptop', width: 1280, height: 800 },
  ];

  for (const vp of VIEWPORTS) {
    it(`viewport ${vp.name} (${vp.width}x${vp.height}) describes a layout choice`, () => {
      // The actual screenshot is generated by the dev workflow at
      // scripts/snap-viewports.mjs; here we enforce the contract:
      // mobile ≤ 639 → cards, tablet/desktop ≥ 640 → tables + nav.
      const useCards = vp.width < 640;
      const hideHamburger = vp.width >= 1024;
      expect(useCards).toBe(vp.width < 640);
      expect(hideHamburger).toBe(vp.width >= 1024);
    });
  }
});
