/**
 * Device authentication: SHA-256 hash compare, constant-time.
 *
 * Tokens are issued by the dashboard (ADMIN-only), generated by the worker,
 * shown once on creation, then stored only as a hash + 4-char prefix.
 *
 * Failure modes are intentionally collapsed into one generic 401 so an
 * attacker cannot enumerate device codes vs. invalid keys.
 */

import type { D1Database, DeviceCredentialRow, DeviceRow } from '@shikoo/database';
import { SQL } from '@shikoo/database';
import { sha256Hex, timingSafeEqual } from '@shikoo/contracts';
import { updateDeviceSeen } from './devices.js';

const HEX = /^[0-9a-f]+$/;

export interface DeviceAuthSuccess {
  ok: true;
  device: DeviceRow;
  credential: DeviceCredentialRow;
}

export interface DeviceAuthFailure {
  ok: false;
  reason: 'unknown_device' | 'invalid_key' | 'revoked' | 'disabled';
}

export type DeviceAuthResult = DeviceAuthSuccess | DeviceAuthFailure;

// Re-export the shared helpers so existing callers (`auth.ts` consumers
// in this worker) don't need a second import edit.
export { sha256Hex, timingSafeEqual };

/**
 * Verify the device + API key, then bump last_seen_at.
 *
 * The body's `deviceName` is deliberately not a parameter: the dashboard owns
 * `devices.display_name` and this used to overwrite it on every message. See
 * the header of `devices.ts`.
 */
export async function authenticateDevice(
  db: D1Database,
  deviceCode: string,
  apiKey: string,
): Promise<DeviceAuthResult> {
  if (!deviceCode || !apiKey) return { ok: false, reason: 'unknown_device' };
  const device =
    (await db.prepare(SQL.findActiveDevice).bind(deviceCode).first<DeviceRow>()) ?? null;
  if (!device) {
    await touchFailure(db, null);
    return { ok: false, reason: 'unknown_device' };
  }
  if (device.active !== 1) {
    await touchFailure(db, device.id);
    return { ok: false, reason: 'disabled' };
  }

  const prefix = apiKey.slice(0, 4);
  const credential =
    (await db
      .prepare(SQL.findActiveCredentialByPrefix)
      .bind(prefix, device.id)
      .first<DeviceCredentialRow>()) ?? null;

  if (!credential || credential.device_id !== device.id) {
    await touchFailure(db, device.id);
    return { ok: false, reason: 'invalid_key' };
  }
  if (credential.status !== 'ACTIVE') {
    await touchFailure(db, device.id);
    return { ok: false, reason: 'revoked' };
  }

  const presentedHash = await sha256Hex(apiKey);
  if (
    typeof presentedHash !== 'string' ||
    !HEX.test(credential.token_hash) ||
    !timingSafeEqual(presentedHash, credential.token_hash)
  ) {
    await touchFailure(db, device.id);
    return { ok: false, reason: 'invalid_key' };
  }

  // Auth passed: bump last_seen_at.
  await updateDeviceSeen(db, device.id);

  return { ok: true, device, credential };
}

async function touchFailure(db: D1Database, deviceId: string | null): Promise<void> {
  if (!deviceId) return;
  await db.prepare(SQL.touchDeviceAuthFailure).bind(deviceId, Date.now()).run();
}

// Re-export the new helpers so callers don't need a second import.
export { markIngested } from './devices.js';

export { tokenPrefix } from '@shikoo/contracts';
